language: smalltalk
sudo: false

smalltalk_config: .smalltalk_gemstone.ston
os:
  - linux
#  - osx
#services: 
#  - mongodb
smalltalk:
   - GemStone-3.3.0
#  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
env: GSCI_CLIENTS="Pharo-5.0"
