language: smalltalk
sudo: false

#os:       #comment out both oses at once - workaround for https://github.com/travis-ci/travis-ci/issues/6028 (see https://github.com/hpi-swa/smalltalkCI/issues/138 for discussion of alternate workarounds)
# - linux
#  - osx
services: 
  - mongodb
smalltalk:
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

matrix:
  include:
    - smalltalk_config: .smalltalk_gemstone.ston
      smalltalk: GemStone-3.3.0
      env: GSCI_CLIENTS="Pharo-5.0"
  allow_failures:
    - smalltalk: Pharo-4.0 # until https://github.com/pharo-nosql/voyage/issues/43 fixed
    - smalltalk: Pharo-3.0 # until https://github.com/pharo-nosql/voyage/issues/43 fixed

cache:
  directories:
    - $SMALLTALK_CI_CACHE
