language: smalltalk
sudo: false

os:
  - linux
#  - osx
services: 
  - mongodb
smalltalk:
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

matrix:
  include:
    - smalltalk_config: .smalltalk_gemstone.ston
      smalltalk: Pharo-5.0
