language: smalltalk
sudo: false

os:
  - linux
#  - osx
services: 
  - mongodb
smalltalk:
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

matrix:
  include:
    - smalltalk_config: .smalltalk_gemstone.ston
      smalltalk: GemStone-3.3.0
      env: GSCI_CLIENTS="Pharo-5.0"
      sudo: false
