language: smalltalk
sudo: false
os: linux
#  - linux
#  - osx

services: 
  - mongodb
smalltalk:
  - Pharo-6.0
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0
smalltalk_config: .smalltalk.ston
matrix:
  include:
    - smalltalk: GemStone-3.3.1
      smalltalk_config: .smalltalk-tugrik.ston
      env: GSCI_CLIENTS="Pharo-5.0"
      cache:
        directories:
          - $SMALLTALK_CI_CACHE
    - smalltalk: Pharo-6.0
      before_script: wget https://raw.githubusercontent.com/pharo-nosql/PunQLite/master/binary/linux/unqlite.so
      smalltalk_config: .smalltalk-unqlite.ston
    - smalltalk: Pharo-5.0
      before_script: wget https://raw.githubusercontent.com/pharo-nosql/PunQLite/master/binary/linux/unqlite.so
      smalltalk_config: .smalltalk-unqlite.ston
  allow_failures:
    - smalltalk_config: .smalltalk-unqlite.ston

#branches:
#  except:
#    - classmapper
