language: smalltalk
sudo: false

smalltalk_config: .smalltalk_gemstone.ston

services: 
  - mongodb
smalltalk:
   - GemStone-3.3.0
#  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
env: GSCI_CLIENTS="Pharo-5.0"
matrix:
  include:
    - smalltalk: Pharo-5.0
      smalltalk_config: .smalltalk.ston
cache:
  directories:
    - $SMALLTALK_CI_CACHE
