language: smalltalk
sudo: false

#os:       #comment out both oses at once - workaround for https://github.com/hpi-swa/smalltalkCI/issues/138
# - linux
#  - osx
services: 
  - mongodb
smalltalk:
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

matrix:
  include:
    - smalltalk_config: .smalltalk_gemstone.ston
      smalltalk: GemStone-3.3.0
      env: GSCI_CLIENTS="Pharo-5.0"

cache:
  directories:
    - $SMALLTALK_CI_CACHE
